import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { MAX_FOUNDER_RECEIPT_TTL_MS, consumeFounderReceipt, issueFounderReceipt, verifyFounderReceipt, type FounderReceiptAuthorityResolver, type FounderReceiptAuthoritySnapshot, type FounderReceiptConsumptionLedger, type FounderReceiptIssueInput, type FounderReceiptSigner, type FounderReceiptVerificationContext } from '../founderReceiptKernel.js';
const SIGNING_KEY='test-founder-receipt-signing-key-32-bytes-minimum'; const SIGNER:FounderReceiptSigner={keyId:'fcr-founder-receipt-test-key',signingKey:SIGNING_KEY}; const HEAD_SHA='a'.repeat(40),OTHER_SHA='b'.repeat(40),SCOPE_HASH='1'.repeat(64),OTHER_SCOPE_HASH='2'.repeat(64); const EVIDENCE_REFS=['evidence:independent-review','evidence:ci']; const ISSUED_AT='2026-08-21T06:00:00.000Z',EXPIRES_AT='2026-08-21T06:15:00.000Z',NOW='2026-08-21T06:05:00.000Z';
function issueInput(overrides:Partial<FounderReceiptIssueInput>={}):FounderReceiptIssueInput{return{receiptId:'receipt-001',decisionId:'decision-001',founderIdentity:'founder@example.com',action:'merge',resource:'jussray/founder-control-room#577',targetSha:HEAD_SHA,scopeHash:SCOPE_HASH,evidenceRefs:EVIDENCE_REFS,expiresAt:EXPIRES_AT,...overrides};} function receipt(){return issueFounderReceipt(issueInput(),SIGNER);} function context(overrides:Partial<FounderReceiptVerificationContext>={}):FounderReceiptVerificationContext{return{decisionId:'decision-001',founderIdentity:'founder@example.com',action:'merge',resource:'jussray/founder-control-room#577',targetSha:HEAD_SHA,scopeHash:SCOPE_HASH,evidenceRefs:EVIDENCE_REFS,now:NOW,...overrides};} function authoritySnapshot(overrides:Partial<FounderReceiptAuthoritySnapshot>={}):FounderReceiptAuthoritySnapshot{return{targetSha:HEAD_SHA,scopeHash:SCOPE_HASH,evidenceRefs:EVIDENCE_REFS,...overrides};} function authorityResolver(snapshot:FounderReceiptAuthoritySnapshot=authoritySnapshot()):FounderReceiptAuthorityResolver{return{resolve:()=>snapshot};} class MemoryLedger implements FounderReceiptConsumptionLedger{private readonly consumed=new Set<string>();claim(receiptId:string):boolean{if(this.consumed.has(receiptId))return false;this.consumed.add(receiptId);return true;}}
describe('FounderReceiptKernel v1',()=>{beforeEach(()=>{vi.useFakeTimers();vi.setSystemTime(new Date(ISSUED_AT));});afterEach(()=>vi.useRealTimers());
it('accepts and consumes one exact FCR-issued receipt when live authority still matches',async()=>{expect((await consumeFounderReceipt(receipt(),context(),SIGNER,new MemoryLedger(),authorityResolver())).ok).toBe(true);});
it('rejects forged, scope escalation, evidence substitution, expiry, and key mismatch',()=>{expect(verifyFounderReceipt({...receipt(),founderIdentity:'attacker@example.com'},context({founderIdentity:'attacker@example.com'}),SIGNER)).toMatchObject({ok:false,code:'RECEIPT_SIGNATURE_INVALID'});expect(verifyFounderReceipt(receipt(),context({targetSha:OTHER_SHA}),SIGNER)).toMatchObject({ok:false,code:'RECEIPT_SCOPE_MISMATCH'});expect(verifyFounderReceipt(receipt(),context({scopeHash:OTHER_SCOPE_HASH}),SIGNER)).toMatchObject({ok:false,code:'RECEIPT_SCOPE_MISMATCH'});expect(verifyFounderReceipt(receipt(),context({evidenceRefs:['evidence:ci','evidence:different-review']}),SIGNER)).toMatchObject({ok:false,code:'RECEIPT_SCOPE_MISMATCH'});expect(verifyFounderReceipt(receipt(),context({now:EXPIRES_AT}),SIGNER)).toMatchObject({ok:false,code:'RECEIPT_EXPIRED'});expect(verifyFounderReceipt(receipt(),context(),{keyId:'other-key',signingKey:SIGNING_KEY})).toMatchObject({ok:false,code:'RECEIPT_KEY_MISMATCH'});});
it('does not let caller choose issuance time and refuses god-mode lifetime',()=>{const untrusted={...issueInput(),issuedAt:'2030-01-01T00:00:00.000Z'} as unknown as FounderReceiptIssueInput;expect(issueFounderReceipt(untrusted,SIGNER).issuedAt).toBe(ISSUED_AT);const expiresAt=new Date(Date.parse(ISSUED_AT)+MAX_FOUNDER_RECEIPT_TTL_MS+1).toISOString();expect(()=>issueFounderReceipt(issueInput({expiresAt}),SIGNER)).toThrow(/no longer than/);});
it('expires authorization when live target, scope, or evidence authority changes',async()=>{const exact=receipt();expect(verifyFounderReceipt(exact,context(),SIGNER).ok).toBe(true);expect(await consumeFounderReceipt(exact,context(),SIGNER,new MemoryLedger(),authorityResolver(authoritySnapshot({targetSha:OTHER_SHA})))).toMatchObject({ok:false,code:'RECEIPT_AUTHORITY_EXPIRED'});expect(await consumeFounderReceipt(receipt(),context(),SIGNER,new MemoryLedger(),authorityResolver(authoritySnapshot({scopeHash:OTHER_SCOPE_HASH})))).toMatchObject({ok:false,code:'RECEIPT_AUTHORITY_EXPIRED'});expect(await consumeFounderReceipt(receipt(),context(),SIGNER,new MemoryLedger(),authorityResolver(authoritySnapshot({evidenceRefs:['evidence:ci','evidence:new-review']})))).toMatchObject({ok:false,code:'RECEIPT_AUTHORITY_EXPIRED'});});
it('fails closed when current authority cannot be resolved',async()=>{const unavailable:FounderReceiptAuthorityResolver={resolve:()=>{throw new Error('provider unavailable');}};expect(await consumeFounderReceipt(receipt(),context(),SIGNER,new MemoryLedger(),unavailable)).toMatchObject({ok:false,code:'RECEIPT_AUTHORITY_UNAVAILABLE'});});
it('rejects replay and unknown authority metadata',async()=>{const ledger=new MemoryLedger();expect((await consumeFounderReceipt(receipt(),context(),SIGNER,ledger,authorityResolver())).ok).toBe(true);expect(await consumeFounderReceipt(receipt(),context(),SIGNER,ledger,authorityResolver())).toMatchObject({ok:false,code:'RECEIPT_REPLAYED'});expect(verifyFounderReceipt({...receipt(),approvedByAgent:'claude'},context(),SIGNER)).toMatchObject({ok:false,code:'RECEIPT_INVALID'});});});
