export type DesiredSwitchState = 'on' | 'off';
export type SwitchControlMode = 'enforced' | 'observe_only' | 'locked_off';
export type SwitchStageState = 'yes' | 'partial' | 'no' | 'unknown';

export interface SwitchStages {
  built: SwitchStageState;
  configured: SwitchStageState;
  active: SwitchStageState;
  proven: SwitchStageState;
}

export interface PortfolioSwitchDefinition {
  id: string;
  project: string;
  repository: string | null;
  label: string;
  summary: string;
  group: 'authority' | 'runtime' | 'product' | 'intelligence' | 'trust' | 'distribution' | 'commerce' | 'portfolio';
  controlMode: SwitchControlMode;
  defaultDesiredState: DesiredSwitchState;
  stages: SwitchStages;
  auditedSha: string | null;
  auditedAt: string;
  evidenceRef: string;
  blocker: string | null;
  offEffect: string;
  onCondition: string;
}

export const SWITCHBOARD_AUDIT_AT = '2026-08-15T05:51:00.000Z';

const FCR_SHA = 'eebdfb718a24fc04b574d28611a62b6041f1d4e6';
const SEKRET_SHA = '802dbcecfa58a9b00e3f2f5605d7161771fd0d81';
const CHIEF_SHA = '0213e89227f72d448a273585fb849c923836d5fa';
const STORY_SHA = '550b16944a77107d91588e67fd8d4870c89bda4c';
const PROMPTOS_SHA = 'deadee5b18fc6b433fee5805554bdba00e175202';
const JBH_PRIVATE_SHA = 'e811e43e41071c6f422cd8f2a950ca5135e6fb99';
const JBH_SITE_SHA = 'c574921e2073bc5511b07dc281284e1f92aaa179';
const UNTOLD_SHA = 'd00fe8c575152bab32dbc5f7ad02575ba9540cd7';

export const portfolioSwitchCatalog: readonly PortfolioSwitchDefinition[] = [
  {
    id: 'fcr-privileged-execution-master',
    project: 'Founder Control Room',
    repository: 'jussray/founder-control-room',
    label: 'Privileged execution master',
    summary: 'Master FCR gate in front of privileged mission execution. OFF is a real server-side kill switch.',
    group: 'authority',
    controlMode: 'enforced',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'yes', active: 'yes', proven: 'partial' },
    auditedSha: FCR_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'src/http/server.ts + V10 approval binding',
    blocker: 'Production exact-SHA runtime remains separately unproven.',
    offEffect: 'Blocks POST /approvals/:missionId/execute before privileged execution can reserve or perform work.',
    onCondition: 'Founder may re-enable only when the intended execution lane remains healthy and separately authorized.',
  },
  {
    id: 'fcr-cloudflare-production-authority',
    project: 'Founder Control Room',
    repository: 'jussray/founder-control-room',
    label: 'Cloudflare production authority',
    summary: 'Credential/configuration gate for the canonical founder-control-room Worker deployment lane.',
    group: 'authority',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'no', active: 'no', proven: 'no' },
    auditedSha: FCR_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #182; exact-main Worker Reconcile failure 31864568036',
    blocker: 'GitHub production environment supplied an empty CLOUDFLARE_API_TOKEN.',
    offEffect: 'FCR records that Cloudflare production authority is not desired; it does not delete or disable the provider Worker.',
    onCondition: 'Least-privilege production token exists and the bounded exact-head workflow proves the current Worker.',
  },
  {
    id: 'fcr-worker-native-git-autodeploy',
    project: 'Founder Control Room',
    repository: 'jussray/founder-control-room',
    label: 'Cloudflare native Worker Git auto-deploy',
    summary: 'Competing provider deployment lane that should remain non-promoting while GitHub exact-head deploy is canonical.',
    group: 'authority',
    controlMode: 'observe_only',
    defaultDesiredState: 'off',
    stages: { built: 'yes', configured: 'unknown', active: 'unknown', proven: 'partial' },
    auditedSha: FCR_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #182 provider authority conflict',
    blocker: 'Authenticated Cloudflare Builds read-back/disconnect state is not yet retained for the current head.',
    offEffect: 'Records the intended non-promoting state. Provider-side disconnect/disable still requires authenticated Cloudflare reconciliation.',
    onCondition: 'Only reconsider if the lane is deliberately redesigned as non-promoting evidence and cannot bypass founder deployment authority.',
  },
  {
    id: 'fcr-exact-production-runtime',
    project: 'Founder Control Room',
    repository: 'jussray/founder-control-room',
    label: 'Exact-current-main production runtime',
    summary: 'Canonical Worker, migration ledger, health, version SHA, and disabled publication grant witnessed on one approved current-main deploy.',
    group: 'runtime',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'unknown', proven: 'no' },
    auditedSha: FCR_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issues #182 and #227',
    blocker: 'Production deploy cannot complete until provider credentials/configuration pass preflight.',
    offEffect: 'Marks current production promotion as undesired; no live Worker is deleted or rolled back automatically.',
    onCondition: 'Exact current main passes deployment authority, migration ledger, /health, /version.gitSha and guardrail proof.',
  },
  {
    id: 'fcr-mission-controller-scheduler',
    project: 'Founder Control Room',
    repository: 'jussray/founder-control-room',
    label: 'MissionController scheduled reconciler',
    summary: 'Cron-driven controller that claims ready outbox work and advances missions only with required evidence.',
    group: 'runtime',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'yes', active: 'unknown', proven: 'no' },
    auditedSha: FCR_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #254',
    blocker: 'Deployed cron registration and real scheduled-event claim path have not been witnessed on exact current runtime.',
    offEffect: 'Records that scheduled reconciliation should not run; Cloudflare cron itself is not altered by this switch.',
    onCondition: 'Exact deployed SHA, active cron, scheduled logs, queue claim, completion/retry and mission transition are retained.',
  },
  {
    id: 'fcr-n8n-conveyor',
    project: 'Founder Control Room',
    repository: 'jussray/founder-control-room',
    label: 'n8n founder conveyor',
    summary: 'External execution conveyor that turns governed handoffs into repeatable workflows with receipts.',
    group: 'runtime',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'unknown', proven: 'partial' },
    auditedSha: FCR_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'src/lib/n8nConveyorReadiness.ts + conveyor Playwright proof',
    blocker: 'Repository readiness exists; live external conveyor execution is not yet a complete exact-SHA receipt loop.',
    offEffect: 'Records that FCR should not route new work to n8n; it does not delete or disable n8n workflows.',
    onCondition: 'Live connector, bounded authority, execution receipt, failure handling and rollback are proven.',
  },
  {
    id: 'fcr-founder-signal-publication',
    project: 'Founder Control Room',
    repository: 'jussray/founder-control-room',
    label: 'Founder Signal autonomous publication',
    summary: 'External social/CRM publication authority. Review-first behavior stays on while autonomous publication stays locked off.',
    group: 'authority',
    controlMode: 'locked_off',
    defaultDesiredState: 'off',
    stages: { built: 'yes', configured: 'partial', active: 'no', proven: 'no' },
    auditedSha: FCR_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issues #97, #118 and #299',
    blocker: 'Registry-backed publication approval and downstream Buffer/Zapier receipt loop are not proven live.',
    offEffect: 'Preserves review/draft-only external behavior and prevents the switchboard from representing publication as authorized.',
    onCondition: 'Code review must first change this catalog after registry-backed approval, exact invocation binding and downstream receipt proof are live.',
  },
  {
    id: 'fcr-main-protection',
    project: 'Founder Control Room',
    repository: 'jussray/founder-control-room',
    label: 'GitHub main protection',
    summary: 'Platform branch/ruleset protection that prevents direct or force-push paths from bypassing founder merge authority.',
    group: 'authority',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'no', active: 'no', proven: 'no' },
    auditedSha: FCR_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #328 last verified platform state',
    blocker: 'Last retained GitHub metadata reported main unprotected with no required status checks/ruleset.',
    offEffect: 'Records that branch protection is not desired; it does not remove GitHub rules.',
    onCondition: 'GitHub reports active protection with intended always-present required checks and no normal bypass.',
  },
  {
    id: 'fcr-vanta-compliance-provider',
    project: 'Founder Control Room',
    repository: 'jussray/founder-control-room',
    label: 'Vanta compliance provider',
    summary: 'Read-only governed compliance evidence provider for SOC 2, ISO/IEC 27001 and HIPAA readiness context.',
    group: 'intelligence',
    controlMode: 'locked_off',
    defaultDesiredState: 'off',
    stages: { built: 'partial', configured: 'no', active: 'no', proven: 'no' },
    auditedSha: FCR_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #99',
    blocker: 'Provider-neutral compliance evidence schema and claim guards are not yet landed and verified.',
    offEffect: 'Keeps Vanta disconnected/unused by FCR.',
    onCondition: 'Land read-only compliance contract, claim guards, redaction and founder-authenticated provider proof first.',
  },
  {
    id: 'sekret-pages-front-door',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'app.sekretbip.net Pages ownership',
    summary: 'Pages frontend owns the app hostname while api.sekretbip.net remains on the canonical sekret-backend Worker.',
    group: 'runtime',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'no', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'PR #825/#832 path; provider reconcile run 31857828587',
    blocker: 'Cloudflare Pages-domain read returned 403/code 10000 before any mutation.',
    offEffect: 'Records that the app front door should not be promoted; it does not detach Pages or Worker domains.',
    onCondition: 'Correct provider authority, exact-host reconcile and production browser proof show Pages owns the app hostname.',
  },
  {
    id: 'sekret-production-schema-verifier',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'Production schema verification',
    summary: 'Exact-main Supabase schema verification before release claims.',
    group: 'trust',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'no', active: 'no', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #795',
    blocker: 'SUPABASE_ACCESS_TOKEN was empty in the production verification lane.',
    offEffect: 'Records release-schema verification as intentionally disabled; it does not change Supabase.',
    onCondition: 'Least-privilege provider secret is restored and exact-main schema verification passes without weakening the gate.',
  },
  {
    id: 'sekret-exact-release-witness',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'Exact production release witness',
    summary: 'One exact deployed SHA witnessed across Pages, canonical Worker, health, Supabase and core live journeys.',
    group: 'distribution',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'unknown', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #696',
    blocker: 'Full exact-current-main production/browser packet has not completed for the current SHA.',
    offEffect: 'Marks production release promotion as not desired; it does not roll back a deployed build.',
    onCondition: 'Pages marker, Worker identity/version, health, Teen/Bip Jr entry and returning-user sign-in pass on one exact SHA.',
  },
  {
    id: 'sekret-account-journey',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'Real account journey',
    summary: 'Signup, confirmation, onboarding, session restore, correct role, logout/login and recovery on the live product.',
    group: 'product',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'yes', active: 'partial', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issues #502 and #563',
    blocker: 'Repository work cannot replace full external Auth/browser/device proof.',
    offEffect: 'Records that account entry should not be considered launch-enabled; it does not disable Supabase Auth.',
    onCondition: 'Controlled live Teen/Parent/founder paths pass confirmation, restore, recovery and device proof.',
  },
  {
    id: 'sekret-bridge-two-account',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'Bridge two-account journey',
    summary: 'Teen-to-parent link/share/revoke path with parent-safe summary and data-layer privacy proof.',
    group: 'trust',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'partial', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #270',
    blocker: 'Controlled two-account production proof remains open.',
    offEffect: 'Records Bridge as not desired for live use; it does not revoke existing provider/database state.',
    onCondition: 'Two controlled accounts prove link, summary-only access, revoke and immediate denial below the UI layer.',
  },
  {
    id: 'sekret-cloud-comfort',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'Cloud + Comfort live journey',
    summary: 'Completed repository UX exercised with permanent account, privacy, recovery, accessibility and physical-device proof.',
    group: 'product',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'yes', active: 'partial', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #507',
    blocker: 'Controlled permanent-account and physical-device acceptance packet remains open.',
    offEffect: 'Records Cloud/Comfort as not desired for release claims; it does not remove routes or user data.',
    onCondition: 'Exact deployed build passes real-account states, privacy, network transitions and device accessibility.',
  },
  {
    id: 'sekret-account-export-deletion',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'Data export + account deletion',
    summary: 'User-facing export/deletion with backend proof across Auth, database, Storage, Bridge, memory and local private state.',
    group: 'trust',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'partial', configured: 'partial', active: 'no', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issues #417 and #426',
    blocker: 'Complete user-facing flow and post-deletion denial proof remain open.',
    offEffect: 'Records deletion/export as not release-ready; it does not block lawful deletion requests already in flight.',
    onCondition: 'End-to-end export/deletion and post-deletion denial are verified on the canonical backend.',
  },
  {
    id: 'sekret-rls-authorization-gate',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'Supabase authorization gate',
    summary: 'RLS, Storage and SECURITY DEFINER denial/allow matrix that protects account and relationship boundaries.',
    group: 'trust',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'partial', configured: 'partial', active: 'partial', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issues #344 and #399',
    blocker: 'Remaining broad-policy and privileged RPC surfaces still require bounded live classification/proof.',
    offEffect: 'Records advanced data-backed features as not authorized to expand; it does not disable existing Supabase access.',
    onCondition: 'Negative authorization matrix and remaining advisor findings are resolved/classified with executable proof.',
  },
  {
    id: 'sekret-l4-continuity',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'L4 companion continuity',
    summary: 'Structured durable companion continuity with provenance, correction, expiry, deletion and one visible user path.',
    group: 'intelligence',
    controlMode: 'locked_off',
    defaultDesiredState: 'off',
    stages: { built: 'partial', configured: 'no', active: 'no', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #357',
    blocker: 'L4 is explicitly gated behind sufficient #399 authorization evidence.',
    offEffect: 'Keeps durable continuity expansion disabled.',
    onCondition: 'RLS gate is sufficient, one reviewed continuity model exists, deletion proof passes and code review unlocks this switch.',
  },
  {
    id: 'sekret-living-voice-timing',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'Living Voice timing handoff',
    summary: 'Precise provider/model/fallback/timing metadata reaches a real living-portrait consumer with safe playback lifecycle.',
    group: 'intelligence',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'partial', configured: 'partial', active: 'partial', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #667',
    blocker: 'Timing/provider metadata and a real living-portrait timing consumer are not fully proven.',
    offEffect: 'Records advanced living-portrait voice coupling as undesired; base voice synthesis remains separate.',
    onCondition: 'Typed timing reaches the Worker/client, playback unload is proven and a real portrait consumer uses it.',
  },
  {
    id: 'sekret-streaming-voice',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'Streaming voice / VAD / barge-in',
    summary: 'Low-latency streaming conversation with endpointing and interruption instead of full-clip request/response.',
    group: 'intelligence',
    controlMode: 'locked_off',
    defaultDesiredState: 'off',
    stages: { built: 'no', configured: 'no', active: 'no', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #810 strategy boundary',
    blocker: 'Current app-facing Voice Bip remains full-clip request/response; streaming is unapproved/experimental.',
    offEffect: 'Keeps streaming, VAD and barge-in out of the verified runtime.',
    onCondition: 'Separate architecture/security/privacy/device review must explicitly promote streaming before this catalog unlocks it.',
  },
  {
    id: 'sekret-governed-media',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'Leonardo + Vimeo governed media',
    summary: 'Approved provider-neutral Parent Resources media with stable Vimeo metadata and truthful local poster provenance.',
    group: 'product',
    controlMode: 'locked_off',
    defaultDesiredState: 'off',
    stages: { built: 'partial', configured: 'no', active: 'no', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issues #459 and #733',
    blocker: 'Founder-approved Vimeo ID, poster provenance/license and fallback inputs are still required.',
    offEffect: 'Keeps new provider-backed media out of the runtime while preserving existing resources.',
    onCondition: 'Approved media inputs, registry, accessibility/privacy contracts and Playwright proof land first.',
  },
  {
    id: 'sekret-store-release',
    project: 'Se’kret Bip',
    repository: 'jussray/Sekret-Bip',
    label: 'App Store + Google Play release',
    summary: 'Consumer distribution gate covering trust spine, real-device QA, store metadata and exact submitted build proof.',
    group: 'distribution',
    controlMode: 'locked_off',
    defaultDesiredState: 'off',
    stages: { built: 'partial', configured: 'partial', active: 'no', proven: 'no' },
    auditedSha: SEKRET_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #420',
    blocker: 'P0 trust/security/production/device/store-readiness packet is incomplete.',
    offEffect: 'Keeps store submission/promotion outside the authorized release state.',
    onCondition: 'Canonical store-readiness checklist is evidence-complete and founder device proof passes before code unlocks this switch.',
  },
  {
    id: 'chief-worker-preview',
    project: 'Chief AI',
    repository: 'jussray/chief-ai-machine',
    label: 'Exact-head Worker preview',
    summary: 'Cloudflare immutable preview for the exact Chief AI head so runtime claims can be bound to code.',
    group: 'runtime',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'no', proven: 'no' },
    auditedSha: CHIEF_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #83',
    blocker: 'Workers Builds fails on current main while the immediate parent had a successful immutable preview.',
    offEffect: 'Records exact-head preview as not desired; it does not disable Cloudflare Workers Builds.',
    onCondition: 'Provider failure is classified and immutable preview /version plus Playwright proof pass for current head.',
  },
  {
    id: 'chief-exact-proof-suite',
    project: 'Chief AI',
    repository: 'jussray/chief-ai-machine',
    label: 'Exact-current proof suite',
    summary: 'Freestyle persistence and Control Room contract lanes refreshed against current Chief main.',
    group: 'runtime',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'yes', active: 'partial', proven: 'no' },
    auditedSha: CHIEF_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #68',
    blocker: 'Required exact-main proof lanes have not been refreshed to the current head.',
    offEffect: 'Records current Chief promotion as undesired; it does not remove existing capability code.',
    onCondition: 'Required exact-head browser/contracts artifacts are green and the Control Room evidence pointer is refreshed.',
  },
  {
    id: 'chief-fcr-executive-context',
    project: 'Chief AI',
    repository: 'jussray/chief-ai-machine',
    label: 'FCR executive-context ingestion',
    summary: 'Chief AI consumes sanitized fresh operational truth from FCR without inheriting execution authority.',
    group: 'intelligence',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'partial', configured: 'partial', active: 'no', proven: 'no' },
    auditedSha: CHIEF_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'FCR issue #98 + Chief capability-plan foundation',
    blocker: 'Stable founder-authenticated executive-context boundary is not yet proven live end to end.',
    offEffect: 'Records cross-system executive ingestion as disabled; Chief remains independently usable.',
    onCondition: 'Sanitized read-only FCR context, project isolation, freshness and live Chief ingestion are verified.',
  },
  {
    id: 'chief-compliance-chief',
    project: 'Chief AI',
    repository: 'jussray/chief-ai-machine',
    label: 'Compliance Chief',
    summary: 'Provider-neutral specialist for SOC 2, ISO/IEC 27001 and HIPAA readiness using bounded evidence.',
    group: 'intelligence',
    controlMode: 'locked_off',
    defaultDesiredState: 'off',
    stages: { built: 'partial', configured: 'no', active: 'no', proven: 'no' },
    auditedSha: CHIEF_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'Chief issue #30',
    blocker: 'Depends on the FCR compliance-evidence/Vanta boundary and claim guards.',
    offEffect: 'Keeps compliance specialist outside active Executive Council claims.',
    onCondition: 'FCR compliance evidence contract is live, claim guards pass and Chief ingestion is verified before catalog unlock.',
  },
  {
    id: 'story-l99-promotion',
    project: 'StoryEngine',
    repository: 'jussray/StoryEngine',
    label: 'Exact-main L99 promotion registry',
    summary: 'Promotion-gate workflow proves capability, federation, runtime and auth contracts on exact StoryEngine main.',
    group: 'runtime',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'yes', active: 'no', proven: 'no' },
    auditedSha: STORY_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issue #52',
    blocker: 'Path-filtered promotion workflow did not run on current main; exact-main dispatch proof remains required.',
    offEffect: 'Records capability promotion as undesired; it does not remove StoryEngine functionality.',
    onCondition: 'Exact-main L99 Promotion Gates passes all required jobs with retained federation receipt.',
  },
  {
    id: 'story-standalone-release-loop',
    project: 'StoryEngine',
    repository: 'jussray/StoryEngine',
    label: 'Standalone release loop',
    summary: 'Idea-to-persisted-output StoryEngine journey proven as its own product before Se’kret doorway integration.',
    group: 'product',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'partial', proven: 'no' },
    auditedSha: STORY_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'issues #12/#52 and current Movie save truth repair',
    blocker: 'Standalone exact-current release/promotion proof is not complete.',
    offEffect: 'Records standalone release as not desired; source remains intact.',
    onCondition: 'Core create/save/output journey and current-main promotion evidence are green before cross-product integration.',
  },
  {
    id: 'promptos-live-provider-runtime',
    project: 'PromptOS',
    repository: 'jussray/promptos',
    label: 'Live multi-provider runtime',
    summary: 'Provider-aware contracts correspond to real connected, authorized and verified provider capabilities.',
    group: 'intelligence',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'partial', proven: 'no' },
    auditedSha: PROMPTOS_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'current main plugin live-state contract #17',
    blocker: 'Closed live-state schemas prevent false claims, but every provider runtime is not independently proven.',
    offEffect: 'Records live provider execution as undesired while preserving local prompt/contract functionality.',
    onCondition: 'Each claimed provider has fresh runtime identity, authorization and operation evidence rather than contract-only state.',
  },
  {
    id: 'jbh-commerce-receipts',
    project: 'JBH Private',
    repository: 'jussray/jbh-private',
    label: 'Commerce receipt loop',
    summary: 'Paid-order/storefront actions emit sanitized exact-SHA receipts into FCR operational truth.',
    group: 'commerce',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'unknown', proven: 'no' },
    auditedSha: JBH_PRIVATE_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'FCR issue #223',
    blocker: 'Production migration/Worker/binding and one authenticated sender-to-ledger receipt remain unverified.',
    offEffect: 'Records new commerce receipt ingestion as undesired; it does not alter Shopify orders or delete ledger history.',
    onCondition: 'Migration, Worker SHA, binding-name presence, health/version and one authorized receipt are retained.',
  },
  {
    id: 'jbh-checkout-production-witness',
    project: 'JBH Storefront',
    repository: 'jussray/jussbeautifulhair-site',
    label: 'Exact-production checkout witness',
    summary: 'Branded storefront routes safely to canonical Shopify checkout with exact-current deployment evidence.',
    group: 'commerce',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'yes', active: 'partial', proven: 'no' },
    auditedSha: JBH_SITE_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'current main #58 + portfolio launch ledger',
    blocker: 'Checkout fix is merged; current production /version and real checkout witness remain separate proof.',
    offEffect: 'Records commerce promotion as undesired; it does not disable Shopify checkout.',
    onCondition: 'Current-main production marker plus desktop/mobile cart/checkout proof are retained.',
  },
  {
    id: 'untold-checkout-production-witness',
    project: 'Untold Stories',
    repository: 'jussray/untold-stories-storefront',
    label: 'Exact-production checkout witness',
    summary: 'Current storefront, cart and checkout journey tied to one exact deployed SHA on desktop and mobile.',
    group: 'commerce',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'partial', proven: 'no' },
    auditedSha: UNTOLD_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'current main exact-SHA receipt core #42 + portfolio issue #39',
    blocker: 'Replacement-foundation checkout and exact production/browser evidence remain incomplete.',
    offEffect: 'Records storefront release promotion as undesired; it does not take Shopify/storefront systems offline.',
    onCondition: 'Current-main route/version plus cart/checkout desktop/mobile evidence pass.',
  },
  {
    id: 'portfolio-juss-os-rollout',
    project: 'Portfolio',
    repository: null,
    label: 'Juss OS project-native rollout',
    summary: 'Goalfix/truthmode/confess/ultrathink/OODA/redteam/Lindy contracts exist as project-native adapters across active repos.',
    group: 'portfolio',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'partial', proven: 'no' },
    auditedSha: null,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'FCR issue #162',
    blocker: 'Every active repository has not yet reached merged adapter or explicit not-applicable/deferred disposition.',
    offEffect: 'Records further rollout as undesired; existing project-native adapters remain intact.',
    onCondition: 'Every active repo has an evidenced adapter or explicit founder-approved disposition.',
  },
  {
    id: 'portfolio-federated-truth',
    project: 'Portfolio',
    repository: 'jussray/founder-control-room',
    label: 'Federated truth receipts',
    summary: 'Repositories emit bounded state/evidence packets that FCR can assess for freshness, confidence and next gates.',
    group: 'portfolio',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'partial', proven: 'partial' },
    auditedSha: FCR_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'FCR main #363',
    blocker: 'The FCR decision surface exists, but not every active repository automatically emits current canonical receipts.',
    offEffect: 'Records federation as undesired; existing receipts remain immutable evidence.',
    onCondition: 'All active repos emit freshness-aware canonical receipts without bespoke manual auditing.',
  },
  {
    id: 'portfolio-auto-reconciliation',
    project: 'Portfolio',
    repository: 'jussray/founder-control-room',
    label: 'Automatic state reconciliation',
    summary: 'Repo/provider/runtime changes become receipts, stale evidence expires, FCR updates decisions, and founder sees only changed gates.',
    group: 'portfolio',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'partial', configured: 'partial', active: 'no', proven: 'no' },
    auditedSha: FCR_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'MissionController + federated truth foundations',
    blocker: 'Scheduled runtime and cross-repo receipt coverage are not yet complete enough to replace manual audit-to-main loops.',
    offEffect: 'Records automatic reconciliation as undesired; manual verification remains available.',
    onCondition: 'Scheduled controller, federated receipts, freshness expiry and bounded changed-decision surfacing are proven end to end.',
  },
  {
    id: 'portfolio-state-evidence-claim',
    project: 'Portfolio',
    repository: 'jussray/founder-control-room',
    label: 'State → Evidence → Claim enforcement',
    summary: 'A completion or release claim is permitted only when the named authoritative evidence covers the claim boundary.',
    group: 'portfolio',
    controlMode: 'observe_only',
    defaultDesiredState: 'on',
    stages: { built: 'yes', configured: 'partial', active: 'partial', proven: 'partial' },
    auditedSha: FCR_SHA,
    auditedAt: SWITCHBOARD_AUDIT_AT,
    evidenceRef: 'truth receipt assessment + project-specific truthful-state repairs',
    blocker: 'The contract is present in several paths but is not yet a universal portfolio execution primitive.',
    offEffect: 'Records universal enforcement as undesired; existing fail-closed claims remain unchanged.',
    onCondition: 'Save/deploy/order/mission/publication/auth/deletion claims all resolve through authoritative witnesses and receipts.',
  },
] as const;

const switchById = new Map(portfolioSwitchCatalog.map((item) => [item.id, item]));

export function findPortfolioSwitch(id: string): PortfolioSwitchDefinition | null {
  return switchById.get(id) ?? null;
}
