import { Buffer } from 'node:buffer';
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { FEDERATED_AGENT_RELAY_V31, GENESIS_PROOF_COOKIE_V31, type FederatedAgentRelayEnvelopeV31 } from '../federatedRelay/v31-types.js';
import { sha256HexV31 } from '../federatedRelay/crypto.js';
import { assertFederatedRelayEnvelopeV31, parseCanonicalRelayV31Json } from '../federatedRelay/validation.js';
import { validateRelayEndpointBindingsV31 } from '../accept.js';

const FCR_SHA = 'a'.repeat(40); const CHIEF_SHA = 'b'.repeat(40); const SIG = Buffer.alloc(64).toString('base64url');
function baseEnvelope(): FederatedAgentRelayEnvelopeV31 { const body='{"note":"hello"}'; return { contract:FEDERATED_AGENT_RELAY_V31,messageId:'11111111-1111-4111-8111-111111111111',ordering:{chainId:'33333333-3333-4333-8333-333333333333',sourceSequence:0,chainPosition:0,logicalOperationId:'44444444-4444-4444-8444-444444444444',relation:{type:'root'}},source:{member:'founder-control-room',repository:'jussray/founder-control-room',branch:'main',headSha:FCR_SHA},target:{member:'chief-ai-machine',repository:'jussray/chief-ai-machine',branch:'main',headSha:CHIEF_SHA},issuedAt:'2026-09-13T15:00:00.000Z',expiresAt:'2026-09-13T15:04:00.000Z',nonce:'22222222-2222-4222-8222-222222222222',disposition:'observe',subject:'hardening',payload:{contentType:'application/json',body,sha256:sha256HexV31(body)},contextFingerprint:'c'.repeat(64),predecessorProofCookie:GENESIS_PROOF_COOKIE_V31,evidence:[],supersedesMessageIds:[],signature:{algorithm:'Ed25519',keyId:'fcr-ed25519-2026-09',valueBase64Url:SIG}}; }

describe('federated relay v3.1 hardening',()=>{
  it('rejects unknown nested identity fields',()=>{ const candidate=baseEnvelope() as FederatedAgentRelayEnvelopeV31 & {source: FederatedAgentRelayEnvelopeV31['source'] & {executionAuthorized:boolean}}; candidate.source.executionAuthorized=true; expect(()=>assertFederatedRelayEnvelopeV31(candidate)).toThrowError(/relay_source_field/); });
  it('requires canonical lowercase head SHAs',()=>{ const candidate=baseEnvelope(); candidate.source.headSha='A'.repeat(40); expect(()=>assertFederatedRelayEnvelopeV31(candidate)).toThrowError(/relay_source_head_sha/); });
  it('rejects duplicate-key raw JSON via canonical-JCS transport',()=>{ expect(()=>parseCanonicalRelayV31Json('{"a":1,"a":1}')).toThrowError(/relay_transport_not_canonical_jcs/); });
  it('requires exact current source and target heads',async()=>{ const candidate=baseEnvelope(); const deps={localIdentity:{member:'chief-ai-machine' as const,repository:'jussray/chief-ai-machine',branch:'main',currentHeadSha:CHIEF_SHA},sourceEvidence:{commitExists:async()=>true,isCommitReachableFromBranch:async()=>true,currentBranchHeadSha:async()=> 'd'.repeat(40)},signatureVerifier:{verify:async()=>{throw new Error('unused');}},receiptSigner:{sign:async()=>{throw new Error('unused');}},ledger:{findByMessageId:async()=>null,accept:async()=>{throw new Error('unused');}}}; await expect(validateRelayEndpointBindingsV31({envelope:candidate,deps})).rejects.toThrowError(/relay_source_head_stale/); });
  it('pins DB lineage and RPC-only accepted-state mutation',()=>{ const sql=readFileSync(new URL('../../../supabase/migrations/20260913163000_federated_relay_v31_authority_hardening.sql',import.meta.url),'utf8'); expect(sql).toContain('relay_chain_participant_pair_changed'); expect(sql).toContain('relay_parent_expired_requires_reconcile'); expect(sql).toContain('security definer'); expect(sql).toContain('revoke insert, update, delete on table public.federated_relay_messages from service_role'); });
});
