-- Provider-history marker only.
-- Production recorded version 20260916082353 when the already-reviewed
-- 20260907170500_harden_residual_trigger_function_authority.sql was applied.
-- The real migration SQL remains in that canonical source file; this marker keeps
-- remote migration history reconcilable without replaying the privilege change.
